[build]
  publish = "/"
  command = ""

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-minify"
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
